# Generated by Django 4.0.5 on 2022-06-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripcion del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=50, verbose_name='Nombre del producto'),
        ),
    ]
