# Generated by Django 4.0.5 on 2022-06-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default=1, max_length=6, primary_key=True, serialize=False, verbose_name='Sku'),
            preserve_default=False,
        ),
    ]
