# Generated by Django 4.0.5 on 2022-06-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_producto_idproducto_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Cantidad de stock'),
            preserve_default=False,
        ),
    ]
