# Generated by Django 4.0.5 on 2022-06-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='urlimg',
            field=models.CharField(default=1, max_length=150, verbose_name='Url de la imagen'),
            preserve_default=False,
        ),
    ]
